---
# vim:ft=ansible:

 - name: assert that we only run on HP
   assert: { that: "ansible_system_vendor == 'HP'" }

   # We look for:
   # 01:00.0 "System peripheral" "Hewlett-Packard Company"
   #  "Integrated Lights-Out Standard Slave Instrumentation & System Support" -r05 "Hewlett-Packard Company" "iLO4"
 - name: Checking for ILO device
   shell: "lspci -m | grep 'Lights-Out' |grep iLO"
   register: ilo_info
   changed_when: False
   check_mode: no

   # We need to get the "iLO4" from the above into a varible
   # using the python split fuction on the '"' character and the 2nd from last
   # element of the resulting array. "|lower" is a Jinja2 filter
 - name: Getting ilo version
   set_fact: ilo_version={{ ilo_info.stdout.split('\"')[-2] |lower }}

 - assert: { that: "ilo_version == 'ilo4'" }

 - name: Identifying firmware for ILO4
   shell: "yum list | grep firmware-{{ ilo_version }} | sort -n +1 -2 | tail -1 | awk '{print $NR}'"
   args:
     warn: False
   register: fw_rpm
   changed_when: False
   ignore_errors: True
   check_mode: false
   when: ilo_version == 'ilo4'

 - name: Starting firmware installer for in "{{ fw_rpm.stdout_lines }}"
   include_tasks: firmware_installer.yml
   with_items: "{{ fw_rpm.stdout_lines }}"
   when: fw_rpm.rc == 0
