---
- name: assert that we only run on HP
  assert: { that: "ansible_system_vendor == 'HP'" }

- name: Identifying firmware RPM for Intel Network controller
  shell: "yum search firmware-nic-intel | grep -i hpe |awk '{print $1;exit}'"
  args:
    warn: False
  register: fw_rpm
  changed_when: False
  ignore_errors: True
  check_mode: false

- name: running generic tasks for all firmware things
  include_tasks: firmware_installer.yml
  with_items: "{{ fw_rpm.stdout_lines }}"
  when: fw_rpm.rc == 0
