---
- name: Identify HP model version
  set_fact:
    hp_gen: "{{ ansible_product_name.split(' ')[2] | lower }}"

- debug:
    msg: "HP model version is: {{ hp_gen }}"

- name: Set HP storage controller utility to ssacli
  set_fact:
    ss_utility: "ssacli"
  when:
    - (hp_gen == "gen8") or (hp_gen == "gen10")

- name: Set HP storage controller utility hpssacli
  set_fact:
    ss_utility: "hpssacli"
  when:
    - hp_gen == "gen9"

- debug:
    msg: "{{ ss_utility }}"

- name: Check that the repos exists
  stat:
    path: '/etc/yum.repos.d/{{ item }}'
  with_items:
    - "rhel-mc.repo"
    - "epel-mc.repo"
    - "redhat.repo"
  register: stat_result

- debug:
    msg: "Repo file exists..."
  when: stat_result.stat.exists

- debug:
    msg: "Repo file not found"
  when: not stat_result.stat.exists  

- name: Install requirement packages
  package:
    name: "{{ item.name }}"
    enablerepo: "{{ item.repo }}"
    state: latest
  loop: "{{ requirement_pkgs }}"  
  when: requirement_pkgs is defined
