---
- name: Identify HP model version
  set_fact:
    hp_gen: "{{ ansible_product_name.split(' ')[2] | lower }}"

- debug:
    msg: "HP model version is: {{ hp_gen }}"

- name: Install requirement packages
  package:
    name: "{{ item.name }}"
    enablerepo: "{{ item.repo }}"
    state: present
  loop: "{{ requirement_pkgs }}"  
  when: install_requirements|bool
